- name: Task level Variables
  hosts: web
  vars_prompt:
    WHO: "Naveen Kumar Reddy Dunthala"
    prompt: Please enter your name
    WHARE: "Benglore"
    prompt: whare you are living prasent
    Working: "software engineer"
    prompt: please enter the duration
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "hey hi i am {{WHO}}, i am from {{WHARE}} and working as a {{Working}}"

  - name: print what you are doing 
    vars:
      DEGRE: "B.Tech"
      WHARE: "Rajampet"
    ansible.builtin.debug:
      msg: "hey i completed {{DEGRE}} from {{WHARE}} and present working as a {{Working}}"

  - name: print information
    ansible.builtin.debug:
      msg: "hey my name is {{WHO}}, i'am living {{WHARE}} and working as a {{Working}}"
  