- name: Variables
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    DURATION: "120HRS"
    WHO : "Naveen Kumar Reddy"
  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "hey, {{WHO}} i am learing {{COURSE}} course ,its duration is {{DURATION}}"